version: '2'

services:
#  auth:
#    build: .
#    ports:
#      - "8082:8082"
#      - "8080:8080"
#    entrypoint: ["java", "-jar", "/opt/app/app.jar"]

  routing:
    build: .
    ports:
      - "8081:8081"
    entrypoint: ["java", "-jar", "/opt/app/routing.jar"]

  helper:
    build: .
    ports:
      - "7777:7777"
    entrypoint: ["java", "-jar", "/opt/app/helper.jar"]

