version: "3.9"

services:
  auth:
    build: .
    ports:
      - "8082:8082"
    expose:
      - "8082"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain auth.AuthMain'"
  routing:
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain routing.RoutingMain'"
  helper:
    build: .
    ports:
      - "7777:7777"
    expose:
      - "7777"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain helper.HelperMain'"