version: "3.9"

services:
  auth:
    build: .
    expose:
      - "8082"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain auth.AuthMain'"
  routing:
    build: .
    expose:
      - "8081"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain routing.RoutingMain'"

  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  routes_db:
    image: "postgres"
    env_file:
      - routes_database.env
    ports:
      - "5433:5433"
    volumes:
      - database-data:/var/lib/postgresql/data/routes_data/


volumes:
  database-data: