services:
  auth:
    build: .
    expose:
      - 8082
    ports:
      - "8082:8082"
    entrypoint: ["java", "-jar", "/opt/service/auth.jar"]
  routing:
    build: .
    expose:
      - 8081
    ports:
      - "8081:8081"
    entrypoint: ["java", "-jar", "/opt/service/routing.jar"]