version: '3'

services:
  routing:
    build: .
    ports:
      - "8081:8081"
    entrypoint: ["java", "-jar", "/opt/app/routing.jar"]

  auth:
    build: .
    ports:
      - "8082:8082"
    entrypoint: ["java", "-jar", "/opt/app/auth.jar"]

#  helper:
#    build: .
#    ports:
#      - "7777:7777"
#    entrypoint: ["java", "-jar", "/opt/app/helper.jar"]

