version: "3.9"

services:
  auth:
    build: .
    expose:
      - "8082"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain auth.AuthMain'"
  routing:
    build: .
    expose:
      - "8081"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain routing.RoutingMain'"

  database:
    image: "postgres"
    env_file:
      - docker-compose/database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  routedatabase:
    build:
      context: .
      dockerfile: Dockerfile-routedatabase
    env_file:
      - docker-compose/routedatabase.env
    ports:
      - "5434:5432"
    volumes:
      - database-data:/var/lib/postgresql/routedata/
#  helper:
#    build: .
#    expose:
#      - "7777"
#    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain helper.HelperMain'"

volumes:
  database-data: