version: "3.9"

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  auth:
    build: .
    expose:
      - "8082"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain auth.AuthMain'"
  routing:
    build: .
    expose:
      - "8081"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain routing.RoutingMain'"
  helper:
    build: .
    expose:
      - "7777"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain helper.HelperMain'"

volumes:
  database-data:

