name: Scala CI
on:
  push:
    branches:
      - master
      - 'release/EgorovGordei/**'
      - 'task/07-CI/EgorovGordei' # DONT FORGET DO DELETE THIS TRIGGER
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: sbt scalafmtCheckAll test:scalafmtCheckAll
